FROM ibsim/base:latest

# Build script amended from https://github.com/tianyikillua/code_aster_on_docker

# Set locale environment
ENV LC_ALL=C.UTF-8 \
    LANG=C.UTF-8 \
    LANGUAGE=C.UTF-8 \
    DEBIAN_FRONTEND=noninteractive \
    PATH="/home/ibsim/VirtualLab/bin:/opt/SalomeMeca/appli_V2019.0.3_universal:/home/ibsim/miniconda3/bin:${PATH}" \
    BASH_ENV=/home/ibsim/patch.sh

# Get Ubuntu updates and basic packages
USER root

RUN sed -i 's/ universe/ universe multiverse/' /etc/apt/sources.list
RUN apt-get update && \
    apt-get upgrade -y --with-new-pkgs -o Dpkg::Options::="--force-confold" && \
    apt-get install -y \
    ubuntu-drivers-common \
    tzdata \
    unzip \
    libglu1 \
    nano \
    git && \
    qt5-default && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY /common/patch.sh /home/ibsim/patch.sh

USER ibsim
WORKDIR /tmp
ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=linux
# Install miniconda instead of full anaconda to space space in final image.
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
bash Miniconda3-latest-Linux-x86_64.sh -b && \
#chmod a+rwx /opt/miniconda3 && \
sudo rm Miniconda3-latest-Linux-x86_64.sh

# uncomment this line and lines to use local copy of slaome instead of downloading every time. 
# Can be useful since the download is flaky
#COPY misc/salome_meca-2019.0.3-1-universal.tgz /home/ibsim/salome_meca-2019.0.3-1-universal.tgz

# Download and install VirtualLab and its requirements
RUN sudo chmod 755 /home/ibsim/patch.sh && \
    wget -O Install_VirtualLab.sh https://gitlab.com/ibsim/virtuallab/-/raw/BT-Container/Scripts/Install/Install_VirtualLab.sh?inline=false && \
    chmod 755 Install_VirtualLab.sh && \
    sudo ./Install_VirtualLab.sh -S y -P c -y && \
    sudo rm /home/ibsim/salome_meca-2019.0.3-1-universal.run && \
    sudo rm /home/ibsim/salome_meca-2019.0.3-1-universal.tgz && \
    mkdir /home/ibsim/flasheur && \
    chmod 777 /home/ibsim/flasheur
USER root

