FROM ubuntu:20.04

ARG mode

RUN (apt-get update && apt-get upgrade -y -q && apt-get dist-upgrade -y -q && apt-get -y -q autoclean && apt-get -y -q autoremove)

RUN apt-get update && apt-get install --no-install-recommends -y software-properties-common  gpg-agent

ENV GCC_VERSION 11

RUN add-apt-repository ppa:ubuntu-toolchain-r/test && apt-get update \
     && apt-get install -y gcc-$GCC_VERSION g++-$GCC_VERSION gfortran-$GCC_VERSION

RUN apt-get update && apt-get install -y --no-install-recommends git wget cmake python3 make libreadline-dev libncurses5-dev ssh ca-certificates curl zsh nano less python3-pip ninja-build

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-$GCC_VERSION 100 --slave /usr/bin/g++ g++ /usr/bin/g++-$GCC_VERSION --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-$GCC_VERSION

RUN git clone https://gitlab.com/libeigen/eigen.git

RUN wget https://registrationcenter-download.intel.com/akdlm/irc_nas/18483/l_onemkl_p_2022.0.2.136.sh

RUN sh ./l_onemkl_p_2022.0.2.136.sh -a --silent --eula accept

RUN wget https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.tar.gz && \
    tar -xzf boost_1_79_0.tar.gz

RUN git clone https://github.com/giacomo-po/MoDELib

RUN cp -r /eigen/Eigen /usr/local/include && \
    cp -r /eigen/unsupported /usr/local/include

RUN cd opt/intel && \
    mkdir mkl && \
    cp -r /opt/intel/oneapi/mkl/2022.0.2/include /opt/intel/mkl

RUN cd opt/intel/mkl && \
    mkdir lib && \
    cp -r /opt/intel/oneapi/mkl/2022.0.2/lib/intel64 /opt/intel/mkl/lib

RUN export LD_LIBRARY_PATH=/opt/intel/mkl/lib/intel64:$LD_LIBRARY_PATH

RUN export LD_LIBRARY_PATH=/opt/intel/lib/intel64:$LD_LIBRARY_PATH

RUN cd MoDELib && \
    rm -r header_symlinks

RUN cd MoDELib/tutorials/DislocationDynamics && \
    cd finiteDomains_NO_FEM/uniformLoadController && \
    make -f Makefile && \
    rm DDomp && \
    rm microstructureGenerator && \
    make DDomp && \
    make microstructureGenerator
