FROM ibsim/base:latest

# Build script amended from https://github.com/tianyikillua/code_aster_on_docker

# Set locale environment
ENV LC_ALL=C.UTF-8 \
    LANG=C.UTF-8 \
    LANGUAGE=C.UTF-8 \
    DEBIAN_FRONTEND=noninteractive \
    PATH="/home/ibsim/VirtualLab/bin:/opt/ERMES/ERMES-CPlas-v12.5:/opt/SalomeMeca/appli_V2019.0.3_universal:${PATH}" \
    BASH_ENV=/home/ibsim/patch.sh

# Get Ubuntu updates and basic packages
USER root

RUN sed -i 's/ universe/ universe multiverse/' /etc/apt/sources.list
RUN apt-get update && \
    apt-get upgrade -y --with-new-pkgs -o Dpkg::Options::="--force-confold" && \
    apt-get install -y \
    ubuntu-drivers-common \
    tzdata \
    unzip \
    libglu1 \
    nano \
    git \
    qt5-default && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY /common/patch.sh /home/ibsim/patch.sh

USER ibsim
WORKDIR /tmp
ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=linux

# uncomment this line and lines to use local copy of slaome instead of downloading every time. 
# Can be useful since the download is flaky
#COPY misc/salome_meca-2019.0.3-1-universal.tgz /home/ibsim/salome_meca-2019.0.3-1-universal.tgz

# Download and install VirtualLab and its requirements
ARG branch=RL_InstallUpdate

RUN sudo chmod 755 /home/ibsim/patch.sh 

RUN wget -O Install_Salome.sh https://gitlab.com/ibsim/virtuallab/-/raw/${branch}/Scripts/Install/Install_Salome.sh?inline=false && \
    chmod 755 Install_Salome.sh && \
    sudo ./Install_Salome.sh && \
    mkdir /home/ibsim/flasheur && \
    chmod 777 /home/ibsim/flasheur

RUN wget -O Install_ERMES.sh https://gitlab.com/ibsim/virtuallab/-/raw/${branch}/Scripts/Install/Install_ERMES.sh?inline=false && \
    chmod 755 Install_ERMES.sh && \
    sudo ./Install_ERMES.sh && \

USER root

