FROM ibsim/base:latest

# Set locale environment
ENV LC_ALL=C.UTF-8 \
    LANG=C.UTF-8 \
    LANGUAGE=C.UTF-8 \
    DEBIAN_FRONTEND=noninteractive \
    PATH="/home/ibsim/VirtualLab/bin:${PATH}" \
    BASH_ENV=/home/ibsim/patch.sh

# Get Ubuntu updates and basic packages
USER root
RUN apt-get update && \
    apt-get upgrade -y --with-new-pkgs -o Dpkg::Options::="--force-confold" && \
    apt-get install -y \
    ubuntu-drivers-common \
    tzdata \
    unzip \
    libglu1 \
    nano \
    python3.8 \
    python3-pip \
    git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY patch.sh /home/ibsim/patch.sh
#expose port 9999 in container for comminucation
EXPOSE 9999
USER ibsim
WORKDIR /tmp
ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=linux
RUN /usr/bin/python3 -m pip install h5py
USER root
