FROM ibsim/base:latest

# Build script amended from https://github.com/tianyikillua/code_aster_on_docker

# Set locale environment
ENV LC_ALL=C.UTF-8 \
    LANG=C.UTF-8 \
    LANGUAGE=C.UTF-8 \
    DEBIAN_FRONTEND=noninteractive \
    PATH="/home/ibsim/VirtualLab/bin:/home/ibsim/miniconda3/bin:${PATH}" \
    BASH_ENV=/home/ibsim/patch.sh

# Get Ubuntu updates and basic packages
USER root

RUN apt-get update && \
    apt-get upgrade -y --with-new-pkgs -o Dpkg::Options::="--force-confold" && \
    apt-get install -y \
    ubuntu-drivers-common \
    tzdata \
    unzip \
    libglu1 \
    nano \
    git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY /common/patch.sh /home/ibsim/patch.sh

USER ibsim
WORKDIR /tmp
ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=linux

RUN sudo chmod 755 /home/ibsim/patch.sh

ARG branch=RL_dev
# Download and install VirtualLab and its requirements
RUN wget -O Install_VirtualLab.sh https://gitlab.com/ibsim/virtuallab/-/raw/${branch}/Scripts/Install/Install_VirtualLab.sh && \
    chmod 755 Install_VirtualLab.sh && \
    sudo ./Install_VirtualLab.sh -b ${branch} -P y -y

ENV PYTHONPATH "/home/ibsim/.local/lib/python3.6/site-packages:${PYTHONPATH}"

EXPOSE 9000
USER root
# RUN mkdir /home/ibsim/VirtualLab/.log
