version: 2.1

jobs:
  init:
    docker:
      - image: cimg/base:2023.08
    steps:
      - run: echo "This is working"

  install_n_test_vlab:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    steps:
      - run:
          name: Prepare Dependency
          command: |
            sudo apt update -y
            sudo apt install -y software-properties-common
            sudo add-apt-repository -y ppa:apptainer/ppa
            sudo apt install -y apptainer python3
            sudo pip3 install pytest
            sudo apt update -y

      - run:
          name: Download Virtual Lab Script
          command: |
            cd
            wget https://gitlab.com/ibsim/virtuallab/-/raw/dev/Scripts/Install/Host/Install_main.sh
            chmod 755 Install_main.sh

      - checkout

      - run: 
          name: Prepare Paths
          command: |
            mv /home/circleci/project /home/circleci/VirtualLab
            cd ~/VirtualLab

      - run:
          name: Run Virtual Lab Script
          command: |
            cd ~/VirtualLab
            sudo DEBIAN_FRONTEND=noninteractive apt-get -yq upgrade
            ~/Install_main.sh -B $(git rev-parse --abbrev-ref HEAD) -y

      - run:
          name: Run Virtual Lab Test
          command: |
            cd ~/VirtualLab
            sudo mkdir -p /usr/share/glvnd
            source ~/.VLprofile
            VirtualLab --test

      - run:
          name: Run Main Tests
          no_output_timeout: 30m
          command: |
            cd ~/VirtualLab
            pytest -s


workflows:
  build_test:
    jobs:
      - init
      - install_n_test_vlab:
          requires:
            - init
