version: 2.1

jobs:
  install_n_test_vlab:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    parallelism: 4 # comment this line to disable parallelism
    steps:
      - run:
          name: Prepare Dependency
          command: |
            sudo apt update -y
            sudo apt install -y software-properties-common
            sudo add-apt-repository -y ppa:apptainer/ppa
            sudo apt install -y apptainer python3
            sudo pip3 install pytest
            sudo apt update -y

      - checkout

      - run: 
          name: Move project to VirtualLab Directory
          command: mv /home/circleci/project /home/circleci/VirtualLab

      - run:
          name: Download and Run Virtual Lab Script
          command: |
            cd ~/VirtualLab
            BRANCH=$(git rev-parse --abbrev-ref HEAD)
            wget https://gitlab.com/ibsim/virtuallab/-/raw/$BRANCH/Scripts/Install/Host/Install_main.sh
            chmod 755 Install_main.sh
            sudo DEBIAN_FRONTEND=noninteractive apt-get -yq upgrade
            ./Install_main.sh -B $BRANCH -y

      - run:
          name: Run Virtual Lab Test
          command: |
            cd ~/VirtualLab
            sudo mkdir -p /usr/share/glvnd
            source ~/.VLprofile
            VirtualLab --test

      - run:
          name: Run Main Tests
          no_output_timeout: 1h
          parallel: true # comment this line to disable parallelism
          when: always
          command: |
            cd ~/VirtualLab
            mkdir -p test-results
            # The next two lines are only needed if you want to run the basic test.
            # chmod 755 tests/test_basic.py
            # chmod 755 RunFiles/Tutorials/basic/Task1_Run.py
            cp -f .circleci/resources/pytest_build_config.ini pytest.ini
            # Comment the next lines to disable parallelism
            TESTFILES=$(circleci tests glob tests/test*.py | circleci tests split --split-by=timings)
            pytest -o junit_logging=system-err --junitxml=test-results/junit.xml $TESTFILES

      - store_test_results:
          path: ~/VirtualLab/test-results

      - store_artifacts:
          path: ~/VirtualLab/test-results


workflows:
  VirtualLab_test:
    jobs:
      - install_n_test_vlab
