#!/bin/bash --login
#SBATCH --job-name=VirtualLab
#SBATCH --output=logs/VL.out.%J
#SBATCH --error=logs/VL.err.%J
#SBATCH --time=0-01:00
#SBATCH --ntasks=4
#SBATCH --ntasks-per-node=4
#SBATCH --mem-per-cpu=6000

'''
This requires creating a conda environment with pytest installed. 
Below are the steps required to create a conda environment called VLTesting:

conda create --name VLTesting python=3.7.0
conda install pytest

'''

# load standard modules
module purge
module load apptainer/#VersionNumber
module load mpi/#MPIVersion # Optional, only required if one wants to run on multiple nodes (set launcher to mpi if so)

# activate conda environment
module load anaconda/#VersionNumber
source /apps/local/languages/anaconda/#VersionNumber/etc/profile.d/conda.sh
conda activate VLTesting # VLTesting can be replaced with name chosen for conda environment
source ~/.VLprofile

# Run pytest on all of VirtualLabs tests
pytest ~/VirtualLab/tests



