FROM ubuntu:20.04

FROM continuumio/miniconda3:4.9.2 as dependencies

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get --allow-releaseinfo-change update
RUN apt-get update -y && \
    apt-get upgrade -y

RUN apt-get install -y libgl1-mesa-glx libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev libosmesa6 libosmesa6-dev libgles2-mesa-dev curl imagemagick && \
                       apt-get clean

ENV PATH /opt/conda/bin:$PATH

ENV CONDA_DEFAULT_ENV pv_env
RUN conda create --name pv_env
ENV PATH /opt/conda/envs/pv_env/bin:$PATH
RUN conda init bash \
    && . /root/.bashrc \
RUN conda activate pv_env && \
    conda install -c conda-forge paraview
